### ISSUE TITLE
Consider content disposition attachment for presigned download link

### ISSUE THREAD

**Issue by victorskl** [umccr/data-portal-apis#142]
Consider content disposition attachment for presigned download link
i.e. `&response-content-disposition=attachment`

See `response-content-disposition` in https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html

**Comment by victorskl** [comment]
Descope from release 2.0 due to other priority. We shall revisit and investigate this in a tad later.

**Comment by victorskl** [comment]
See also https://github.com/umccr-illumina/stratus/issues/121

**Comment by williamputraintan** [comment]
Happy to continue on this. I suppose this issue require changes in libica?

Ref: 
- https://github.com/umccr/data-portal-apis/blob/924eae400be06b3760a96d3443693099a2ea27d9/data_portal/viewsets/gdsfile.py#L40
- https://github.com/umccr-illumina/libica/blob/98fbe51cda7259d35513aa5bc86012f4978c2122/libica/app/gds.py#L181

**Comment by victorskl** [comment]
Yup, Will. Could you please check; through GDS API, whether we could request presign with either (browser) _inline_ or, it is always _attachment_ content deposition.

It might need to do a bit of isolated CLI/curl or JS/iframe testing there for what is happening now and any possible workaround/solution...

**Comment by williamputraintan** [comment]
> Yup, Will. Could you please check; through GDS API, whether we could request presign with either (browser) _inline_ or, it is always _attachment_ content deposition.

Hmmm, from the comment here seems that it should support other `content-disposition`

**Comment by victorskl** [comment]
See convo in this Slack thread -- https://umccr.slack.com/archives/CP356DDCH/p1677563982961669?thread_ts=1677476635.509959&cid=CP356DDCH


> William Putra Intan:
> But it is because of the content-type was set to binary/octet-stream . So the browser thought that it could not be viewed despite of HTML.

My "wild guess"; GDS File PreSigned URLs are customised such that assuming all files get downloaded. 

BYOB would solve this, one way. But. That's in future.

It is pain-in-the-neck for end user; who get to click around to manage those that get downloaded reports and, managing manually in local workstation.

Reopening this UX degradation. Let us go full length of our best to workaround this!

**Comment by victorskl** [comment]
> My "wild guess"; GDS File PreSigned URLs are customised such that assuming all files get downloaded.

Turned out -- this is not about how GDS performing PreSigning behaviour. For some reason, DRAGEN analysis pipeline outputs were forced with MIME ContentType `binary/octet-stream`.

Added GDS PreSigned Override with [libica-2.2.1](https://github.com/umccr-illumina/libica/releases/tag/2.2.1) to counter/workaround this.

ditto as follows.

- https://umccr.slack.com/archives/CP356DDCH/p1679615789632709
- https://github.com/umccr-illumina/libica/blob/c95e648bae4ed9c1f18d4253797678d3e304fdd4/examples/gds_gen_presigned_with_temp_cred.py#L11-L34
