### ISSUE TITLE
Improve ICA pipeline slack message title

### ISSUE THREAD

**Issue by victorskl** [umccr/data-portal-apis#149]
Disambiguate ICA pipeline slack message title between sequence run BSSH event and workflow automation events

Workflows automation related messages
-  **Portal Workflow Automation**

Sequence Run
- **BSSH Sequence Run** (?)

Suggestion welcome

**Comment by skanwal** [comment]
Thanks Victor.
We can go with BSSH Run - excluded Sequence since it is part of `BSSH` (BaseSpace Sequence Hub).
