### ISSUE TITLE
Unresolved attribute reference 'id' for class 'Workflow' 

### ISSUE THREAD

**Issue by alexiswl** [umccr/data-portal-apis#154]
The following line of code is giving me a warning in PyCharm:

https://github.com/umccr/data-portal-apis/blob/986da7707d3673ddde2ca02da9319a5351031250/data_processors/pipeline/lambdas/germline.py#L120

Looking at models.py below, there is no 'id' attribute.  Should I move `.id` to another attribute?

https://github.com/umccr/data-portal-apis/blob/986da7707d3673ddde2ca02da9319a5351031250/data_portal/models.py#L372-L395

**Comment by victorskl** [comment]
>Should I move .id to another attribute?

Nop. `id` for each Model is implicit [Django Automatic primary key (PK) fields](https://docs.djangoproject.com/en/3.1/topics/db/models/#automatic-primary-key-fields). So please leave them be. 

Regarding PyCharm, please try "Enable Django support" through preference to see if that warning got away. 

https://www.jetbrains.com/help/pycharm/django-support.html

**Comment by alexiswl** [comment]
Okay will see if that fixes it!
