### ISSUE TITLE
Implement nested LabMetadata API endpoints for Subject view

### ISSUE THREAD

**Issue by victorskl** [umccr/data-portal-apis#193]
### Explain:

- Subject view (or `/subjects` endpoint) is logical representation API endpoint
- Logical representation means it does not have any backing Django Model.
- A Subject has many sub-resources (typically pulling in those physical models). For example, a Subject has
  - many S3Object(s)
  - some GDSFile(s)
  - few related LIMSRow(s)
  - so and so forth

- Current Subject API route defined as:

```
GET all subjects - http://localhost:8000/subjects/
GET a subject    - http://localhost:8000/subjects/<id>
```

- Subject list are a distinct query of all subject IDs from LIMSRow model. i.e. this is equivalent of [`select distinct` in SQL](https://www.google.com/search?q=select+distinct) -- whereas any equivalent for Django ORM query.

- Typically, after you have your data Model, you implement the related Model backing primary API view such as https://github.com/umccr/data-portal-apis/issues/192

- Then, you may have further use case to show some subset of your Model entities, as nested part of Subject view. This is achieved by using [DRF nested router](https://www.google.com/search?q=django+rest+framework+nested+router). 

- Depends on size of nesting related cardinality between your Model and a Subject, you can flatten the view or nested the view when rendering API representation.

**flatten related entities in the view**
- It is the case for a Subject has few related LIMSRow(s). Since we know that only a handful of LIMS rows will be related to a particular subject, hence, we flatten it directly on `GET http://localhost:8000/subjects/<id>` in a [Subject retrieve(...)](https://github.com/umccr/data-portal-apis/blob/dev/data_portal/viewsets.py#L188).
- This effectively serve related LIMSRow(s) upon just **one** REST call:
```
GET /subjects/<id>
```

**nesting related entities in the view**
- It is the case for a Subject has many S3Object(s). Therefore, it is added as [nested router](https://github.com/umccr/data-portal-apis/blob/dev/data_portal/urls.py#L22) under Subject route and, implement [related backing viewset](https://github.com/umccr/data-portal-apis/blob/0580ef98530fd67ccb838afe2d6331d0e837ade2/data_portal/viewsets.py#L205).
- This effectively serve related/nested S3Object(s) upon 2 (or more) REST calls:
```
GET /subjects/<id>
GET /subjects/<id>/s3
GET /subjects/<id>/s3/<id>
```

### Objective:
This task is to implement related `LabMetadata` rows for a Subject by adapting either one of scheme as explained above.

### Note:
The same scheme/principal is applied to Run view whereas every related entities is nested. Please do observe with:
```
GET http://localhost:8000/runs/
GET http://localhost:8000/runs/<id>
```

**Comment by victorskl** [comment]
@andrei-seleznev This will probably be next after #192. Also /cc FYI for @reisingerf @alexiswl and @brainstorm And, it is probably the same for Report model as well. Happy to run details / chat, if any.

**Comment by victorskl** [comment]
@andrei-seleznev Today we decided to deprecate nested route scheme #196 #197 We rather find it redundant to maintain these. So that invalidate this ticket. If you haven't done so then do not worry about this anymore.

**Comment by andrei-seleznev** [comment]
I'd actually done this already - submittign a pull reuqest just in case its useful down the track!

**Comment by victorskl** [comment]
No worries; I will still merge in. Then, refactor later. At least, it gets into base branches history -- if we might ever need it again in future! I will review PR soon, thanks.

**Comment by victorskl** [comment]
Done
