### ISSUE TITLE
Rename WorkflowType GERMLINE

### ISSUE THREAD

**Issue by victorskl** [umccr/data-portal-apis#226]
Context:

- Current `GERMLINE` workflow is rather `DRAGEN_WGS_QC`
- We may still keep current `GERMLINE` [workflow type enum](https://github.com/umccr/data-portal-apis/blob/dev/data_processors/pipeline/constant.py#L38)
- However, one-off migration is need to rename existing database table to reflect the changes

Actions:

- Preform rename refactor throughout pipeline codebase
- Run data migration SQL / script to reflect existing workflow runs

**Comment by reisingerf** [comment]
While we are at it, do we have a naming scheme for future workflows?
E.g. do we want to reuse existing `GERMLINE` / `TUMOR_NORMAL` or use something like `DRAGEN_WGS_NORMAL` / `DRAGEN_WGS_GERMLINE` and `DRAGEN_WGS_SOMATIC`?
How about wts and tso? (`DRAGEN_WTS`? `DRAGEN_TSO`? `DRAGEN_TSO_RNA`? `DRAGEN_CT_TSO_DNA`? `DRAGEN_TSO500`? ...)

**Comment by reisingerf** [comment]
cc @alexiswl @skanwal

**Comment by victorskl** [comment]
Florian propose these; and will be using these; otherwise please chime in if any.

> Florian Reisinger
> Currently using something like:
> - dragen_wgs_qc
> - dragen_wgs_somatic
> - dragen_wgs_normal or dragen_wgs_germline
> - bcl_convert
> - dragen_wts

I will start refactor WorkflowType `GERMLINE` to `DRAGEN_WGS_QC`

**Comment by reisingerf** [comment]
Thanks Victor!

I think we said `dragen_wgs_germline` rather than `dragen_wgs_normal`, but happy to put that up for vote/discussion

Also, we need one (or more) names for the TSO workflow(s). 
`dragen_tso_ct_dna` and `dragen_tso_dna` for ct vs solid?
Are there equivalent `dragen_tso_ct_rna` and `dragen_tso_rna` ?

/cc @ohofmann

**Comment by ohofmann** [comment]
Vote for `dragen_wgs_germline`, `dragen_tso_solid` and `dragen_tso_liquid` (or `dragen_tso_dna` and `dragen_tso_ctdna`).

**Comment by alexiswl** [comment]
At the moment we've only got the ctdna / liquid automated (I don't think we have many of the solid samples and haven't got a timeline for when we create that workflow in CWL). Solid samples can also be RNA and would run through the exact same pipeline as DNA samples. tso liquid would only be DNA (ctDNA) samples

**Comment by victorskl** [comment]
Update:
- Renamed GERMLINE to DRAGEN_WGS_QC activity on Portal side is completed.

Todo: 
- Follow up to update DRAGEN_WGS_QC workflow input json changes once this PR is finalised
  - https://github.com/umccr/infrastructure/pull/150

**Comment by victorskl** [comment]
Closing this as `GERMLINE` is now renamed to `DRAGEN_WGS_QC` with release `0.3.0`
