### ISSUE TITLE
Use `InstrumentRunID` instead of `name` in SequenceRun

### ISSUE THREAD

**Issue by reisingerf** [umccr/data-portal-apis#243]
In a `bssh.runs` event a sequence run has 3 identifiers:
- id
- name
- instrumentRunId

where the latter have usually the same value.
As the origin of the `name` is not fully known (whereas the `instrumentRunId` is generated by the sequencer itself), it is best not to rely on or use the `name`

See SequenceRun model [here](https://github.com/umccr/data-portal-apis/blob/c31d12b5fe8d66bcf5a677fef3dc2734cfe0f4b3/data_portal/models.py#L480) and

**Comment by victorskl** [comment]
Note: this is taking place as on-going rolling refactor as it comes along throughout code base.

**Comment by victorskl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [OrcaBus V1: Implement SequenceRunManager microservice app](https://trello.com/c/TQX8yJuc/1445-orcabus-v1-implement-sequencerunmanager-microservice-app)

**Comment by victorskl** [comment]
Triaged to OrcaBus Trello storyline & included in SequenceRunManager implementation. Closing.
