### ISSUE TITLE
Remove "project" from analysis and data storage

### ISSUE THREAD

**Issue by reisingerf** [umccr/data-portal-apis#257]
Samples can change (or be part of multiple) projects, however this info is not strictly necessary for data processing.
Currently a change of project involves a serious of (error prone) steps as files/folders have to be changed/moved.

In order to support more flexible project associations and avoid the need for costly data changes, we should look at removing the project from the analysis pipelines. E.g. remove from SampleSheet, don't create project subfolders for BCL Convert output. Perhaps anything else?

**Comment by reisingerf** [comment]
@alexiswl for the BCL Convert workflow, that is as simple as setting the `bcl_sampleproject_subdirectories_bcl_conversion` flag to `false`, i.e. update the input template in SSM ParameterStore to include that input parameter, right?

**Comment by victorskl** [comment]
https://github.com/umccr/infrastructure/compare/bec03c09f336...2ffa00e428a6

**Comment by victorskl** [comment]
I reckon, this consider done and close, yes? @reisingerf

**Comment by victorskl** [comment]
@reisingerf Could you please verify this from SEQ-II validation run. If this is good, could you update it for PROD, pls. Thanks

**Comment by reisingerf** [comment]
Yup! 
FASTQs are now directly in the assay folders:
`gds://development/primary_data/200612_A01052_0017_BH5LYWDSXY/TSO-DNA_TSODNA/NTC_TSO200609VD_L2000559_S8_L003_R1_001.fastq.gz`

No more project dependency.
The `prod` SSM parameter is updated and deployed.

**Comment by victorskl** [comment]
Thanks Flo; saw the commit https://github.com/umccr/infrastructure/commit/dd1023513803ed8925aa26c158e5a82ac6c88da9 

Closing...
