### ISSUE TITLE
 Automated ICA service token rotation

### ISSUE THREAD

**Issue by victorskl** [umccr/data-portal-apis#258]
**Context:**

Portal need ICA service token (JWT) for the following purpose:

1. Generating PreSigned URL request for GDS file
2. Workflow Automation Orchestration
3. All communication to ICA services (WES, GDS, TES, etc..)

**Issue:**

- If service token expired, aforementioned services will be disrupted

**Solution:**

Automated service token rotation can be possibly done as follows:

1. Create long term API key and store it in Secret Manager
2. Implement [AWS Lambda with EventBridge](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-run-lambda-schedule.html) cron event to schedule generate service JWT token
3. Update generated JWT token into SSM parameter store path

**Comment by victorskl** [comment]
4. We can consider also using "Refresh token" if that avail from ICA token endpoint

**Comment by andrewpatto** [comment]
This is pretty much done.

So currently it sets up two Secrets in secrets manager - a master API key that can only have values Put. And a JWT secret - that uses SecretManager rotations (daily) to generate a new JWT value.

It uses randomly named secrets at the moment which is probably a problem - need to know what naming conventions we might want to use for secrets.

We can also have it simultaneously fill in the parameter store JWT value - so can be fully backwards compatible with existing setup.

**Comment by victorskl** [comment]
**Update:**
- Thanks Andrew for bringing this to independent stack; so that ICA token rotator service can be used in different app/workflow.
- Implementation is happening in https://github.com/umccr/infrastructure/pull/162 and, as well in #rc channel.
- Secrets Manager sound good. We can make Portal to read it from Secrets Manager, yes.

**Action:**
- Just need trace [this constant variable](https://github.com/umccr/data-portal-apis/blob/dev/utils/ica.py#L12) usage and replace its access mechanism with Secrets Manager
- Perhaps, `libsm` in `utils` package to follow suit like others such as [`libssm`](https://github.com/umccr/data-portal-apis/blob/dev/utils/libssm.py) 
- Marking to include it in next iteration Release `0.5.0`
