### ISSUE TITLE
Migrate standard ctTSO workflow to coupling workflow

### ISSUE THREAD

**Issue by victorskl** [umccr/data-portal-apis#260]
**Action:**

- Further hook post analysis as sub workflows into the standard ctTSO workflow
- Work is more on CWL workflow side with @alexiswl 
- Once extended ctTSO CWL workflow is ready, just need update new workflow version name in Portal automation side

**Comment by alexiswl** [comment]
https://github.com/umccr/infrastructure/pull/159

**Comment by victorskl** [comment]
Thanks for update, Alexi

**Next:**
- Pending validation run in DEV

**Comment by victorskl** [comment]
@alexiswl Validation run with Run 157 is good, ref #data-portal channel for update. Could you update for PROD now, pls. Thanks.

**Comment by alexiswl** [comment]
Can I wait for https://github.com/umccr/infrastructure/pull/159 to be completed and then I'll put in the infrastructure PR

**Comment by victorskl** [comment]
Ah, ok, of course. Actual task tickie is #263 

_The ball is at Flo court! Flo, pls make a serve..._ @reisingerf 😅

**Comment by victorskl** [comment]
_Flo [have served](https://github.com/umccr/data-portal-apis/issues/263#issuecomment-908046456)! (ACE!) fifteen-love_ 

Ping @alexiswl 

😁

**Comment by victorskl** [comment]
Done with https://github.com/umccr/infrastructure/pull/161

Closing...
