### ISSUE TITLE
Implement T/N + umccrise workflow automation step

### ISSUE THREAD

**Issue by victorskl** [umccr/data-portal-apis#261]
**Context:**

Next iteration of ICA pipeline:

- To add T/N + umccrise workflow automation step into the pipeline

**Actions:**

- Implement CWL workflow
- Implement orchestration logic

**Participants:**
@scwatts @alexiswl @reisingerf @victorskl

**Comment by alexiswl** [comment]
This one's a little more complex since we need to collect the germline vcf of a sample (that we don't currently get from the dragen somatic workflow).  

How far off is 'sample-status' views? Otherwise it's the same as the T/N logic except instead of fastq list rows we're looking for vcfs / bams for each of the tumor and the normal and completion of secondary analysis runs for both the tumor and normal samples (which is why the status view is quite useful)

**Comment by reisingerf** [comment]
The status was next on the list... I'd like to use this case as a (another) reason to push for it.
I think Victor already started it. Happy to have a chat and see if we can get it in.

**Comment by alexiswl** [comment]
Had a chat with Oliver yesterday about this. We could instead run a 'germline+umccrise' pipeline, when tumor-somatic sample comes off the pipeline, kick off the umccrise pipeline with the output directory of the tumor pipeline as the input to the somatic vcf and bam, and take in the fastq list rows used for the normal to then run the germline pipeline and umccrise pipeline. Yes it means that the normal somatic pipeline is run every time for every tumor that it matches, but that's not necessarily a bad thing, guarantees that the normal was processed with the same version of dragen as the tumor was.

**Comment by reisingerf** [comment]
I see, it's basically not treating the normal/germline as separate pipeline, but as pre/prep step to umccrise (run as one workflow)?
Yes, that could work.

Might have the added bonus that we don't need to add/orchestrate another workflow.

**Comment by victorskl** [comment]
Related https://github.com/umccr/cwl-ica/pull/54

**Comment by alexiswl** [comment]
Orchestration logic should be much simpler than what we have for T/N pipeline. Every dynamic input is in the workflow body of the T/N pipeline that will trigger this workflow.  

* Input germline fastq list rows will be the inputs from the T/N pipeline.
* Input dragen somatic directory will be the output directory from the T/N pipeline.  
* Subject ID can be easily obtained.  
* All other input paramaters are static.

**Comment by reisingerf** [comment]
> Input dragen somatic directory will be the output directory from the T/N pipeline.

Do we have a mechanism to retrieve this otherwise? 
Just thinking about when this workflow is triggered manually instead of an (automatic) follow up of the T/N.

**Comment by alexiswl** [comment]
Do we have examples of other lambda calls that can retrieve inputs to a workflow? Or outputs to a workflow?

**Comment by reisingerf** [comment]
Not really.
I think this is the first workflow that depends on the output (not only the data) of a specific previous workflow. So far all inputs where pretty deterministic and independent of any particular workflow: subject ID, library ID, FASTQs (looked up by subject/library ID), sequencing ID, ... 
This time we need a specific output (directory) of a particular workflow... and that may be the answer right there: the info could easily be retrieved using the `portal_run_id`... or via manual DB lookup...

**Comment by alexiswl** [comment]
> I think this is the first workflow that depends on the output (not only the data) of a specific previous workflow. 

ctTSO has this as well, (we require the samplesheet generated in the BCLConvert step that created the ctTSO samples), which is a little more complicated but could use the same method as above.

**Comment by alexiswl** [comment]
> This time we need a specific output (directory) of a particular workflow... and that may be the answer right there: the info could easily be retrieved using the portal_run_id... or via manual DB lookup...

But would we not need to know the ica workflow run id / portal run id that ran the tumor normal in the first place in order to query this?

**Comment by reisingerf** [comment]
> But would we not need to know the ica workflow run id / portal run id that ran the tumor normal in the first place in order to query this?

Yes, but then that's a requirement, i.e. you can't run the post-processing of previous outputs without (somehow) pointing/identifying those previous outputs.
In the regular case there will only be one set of T/N outputs, so that should be easily identifiable (just by subject/lib id). In case there is ambiguity, you'd have to say which one to use (either by pointing directly to the output folder or by providing the workflow/portal run id).
