### ISSUE TITLE
Migrate ctTSO reference data

### ISSUE THREAD

**Issue by victorskl** [umccr/data-portal-apis#263]
- Migrate ctTSO reference data volume
- See https://github.com/umccr/infrastructure/pull/159

**Comment by victorskl** [comment]
@alexiswl If you can (on-the-way), pls help update this too? It is the one left uncheck from [this PR](https://github.com/umccr/infrastructure/pull/159) for PROD. Thankie!

**Comment by alexiswl** [comment]
Yep, need someone with write permissions to copy over the reference data to the production project.

**Comment by reisingerf** [comment]
Copying....

**Comment by reisingerf** [comment]
Completed!

**Comment by victorskl** [comment]
thkz Flo, closing...
