### ISSUE TITLE
Revisit and complete `workflow` annotation when deciding on workflow execution

### ISSUE THREAD

**Issue by reisingerf** [umccr/data-portal-apis#272]
Libraries carrying a `qc` workflow annotation should only run the QC workflow, not any other following workflows, even if possible. 

Similarly, libs annotated with `manual` should be completely excluded from automated processing.

**Comment by alexiswl** [comment]
QC workflow being the dragen_wgs_qc workflow?

**Comment by victorskl** [comment]
- If we look at it by step modules `dragen_tso_ctdna_step` and `dragen_wgs_qc_step` handle these quite explicitly.
- For `tumor_normal_step`, it is implicit by query filter; also mention in #274 
- So, we does these by a crude way, at the mo. I will think of a better way to handle this. (higher order or abstraction or AOP point-cut, _umm now this sound started interesting, rubbing hands!_)

**Comment by reisingerf** [comment]
HaHa! Let me know before you get started though. I have a few ideas around this.

**Comment by victorskl** [comment]
As of eb8ad93444df342ffa8de8cd707f3a0d22aaec09  we introduce domain rule mechanism. It looks and works like this... I will keep open this ticket for more completeness implementation throughout other aspect of domain validation needs.

https://github.com/umccr/data-portal-apis/blob/eb8ad93444df342ffa8de8cd707f3a0d22aaec09/data_processors/pipeline/orchestration/dragen_wgs_qc_step.py#L74-L91

**Comment by victorskl** [comment]
As of 6d2639036dd6e13648590089130099f86a2bd847  we also adopted `SequenceRule`. One example use case implemented as follows:

https://github.com/umccr/data-portal-apis/blob/6d2639036dd6e13648590089130099f86a2bd847/data_processors/pipeline/lambdas/sqs_iap_event.py#L96-L109

**Comment by victorskl** [comment]
This consider partly fix. However, to be considered in [OrcaBus](https://github.com/umccr/orcabus) from ground up.

**Comment by victorskl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [OrcaBus V1: Implement workflow manager microservice application](https://trello.com/c/VBxbUDD2/1436-orcabus-v1-implement-workflow-manager-microservice-application)

**Comment by victorskl** [comment]
In the current generation Portal Pipeline, this has workaround implemented with code construct `XxDomainRule` as explained above.

**Comment by victorskl** [comment]
Triaged to OrcaBus Trello storyline. 

It becomes part of OrcaBus design "Workflow Planner Interface" concept as ground up - whereas it gives "dryrun" or "template" execution plan as soon as there exists sufficient meta information. 

Closing.
