### ISSUE TITLE
Fix issue of duplicate LIMS entries for same library across different lanes

### ISSUE THREAD

**Issue by reisingerf** [umccr/data-portal-apis#273]
Currently we create a LIMS record for each FastqListRow generated by the BCL Convert workflow. That was fine until we allowed the same library ID (without `_topup` extension) to be used across multiple lanes, as we had one FastqListRow for each unique library ID, now there can be multiple.

To fix this we could consider using a set instead of a list here:
https://github.com/umccr/data-portal-apis/blob/33860d4300aacee2017067f370d2597c80b4ae4e/data_processors/pipeline/orchestration/google_lims_update_step.py#L48

**Comment by victorskl** [comment]
- This ironically spot the issue #276 though
- But, yep, let do this now. Since, we can keep side track of whether QC merged run, or not in #276 

Next:
- Going hot with patch Release `0.4.1` 😉
