### ISSUE TITLE
T/N pairing: Expose T/N pairing result as JSON format in API endpoint

### ISSUE THREAD

**Issue by victorskl** [umccr/data-portal-apis#275]
**Context:**

- Likewise _plain_ FASTQs list by Runs in [Examples](https://github.com/umccr/data-portal-apis/tree/dev/docs/examples)
- Expose API endpoint, that Portal have used for preparing T/N job list for WES

**Action:**

- Impl API endpoint

**Comment by reisingerf** [comment]
While we are at is we could restructure the code to cater for additional use cases, e.g. create pairing for a subject, a sequence run, all outstanding samples, selected samples or selected libraries.
Can do in separate step as well....

**Comment by reisingerf** [comment]
The logic for the per subject pairing should already be there.
But yes, start with what's easy to do. Happy to help out with the rest!
