### ISSUE TITLE
Add negative control samples to WGS QC and WTS workflows launching

### ISSUE THREAD

**Issue by victorskl** [umccr/data-portal-apis#295]
**Context:**

Currently we skip NTC samples:

https://github.com/umccr/data-portal-apis/blob/a714546e6b0a6289c0fafdf82dc50af5c4cfda1e/data_processors/pipeline/orchestration/dragen_wgs_qc_step.py#L90-L93

**Changes:**

- Allow negative control samples for WGS QC and WTS workflows

**Comment by reisingerf** [comment]
Fixed by #296 and #297
