### ISSUE TITLE
Retrieve data from RedCap via Data Portal

### ISSUE THREAD

**Issue by andrei-seleznev** [umccr/data-portal-apis#317]
sub-task of epic https://github.com/umccr/data-portal-apis/issues/285

For PieranDX upload we need to (as issue abvove)
1 Get relative files from ctTSO output dataset to be uploaded to PierianDx in portal
2 Get metadata from redcap in portal
3 Send to AWS Fargate / AWS Batch that will upload ctTSO data to PierianDx

For 2: ideally do not want to store redcap into in dataportal (but will do so if needed/api too slow/other issues)

TODO dataportal lambda to call a service that retrieves data from RedCap based on (whatever input we can get from (1), sample name perhaps) and returns it

**Comment by andrei-seleznev** [comment]
WIP branch: **pycap-redcap-pulldata**

**Comment by andrei-seleznev** [comment]
We havea lambda for fetching a redcap database asa dataframe. in branch **pycap-redcap-pulldata** see:
data_processors/lims/lambdas/tests/test_redcapmetadata.py 

It shows a "get me a dataframe from redcap where subjectid in [list]".

currently redcap access is mocked, still waiting for creds.
upon recieving it, TODO:
1. sort out credentials for dataportal itself? (can just read an ENV VAR in the meantime?)
2. put credentials it so we can get them as: libssm.get_secret(const.REDCAP_API_KEY)  
2. get confirmation of DB name and relevant fields to fetch

**Comment by andrei-seleznev** [comment]
@alexiswl  see latest
https://github.com/umccr/data-portal-apis/tree/pycap-redcap-pulldata

you pass it a string of library IDs
you get back a sheet for PieranDX 
TODO s for it
 - actual fields still being worked out
 - u will need to plug service user/your own API token in eventually (currently mocked) 

See test:
  python manage.py test data_processors.lims.lambdas.tests.test_redcapmetadata.RedcapUnitTests.test_handler_by_library_id  
  
...that demonstrated the whole shebang

**Comment by andrei-seleznev** [comment]
parameters for AndreiTest Redcap DB and key are now in parameter store

**Comment by victorskl** [comment]
@andrei-seleznev As discussed; when you are able; implementation in this branch shall now redirect to [cttso-ica-to-pieriandx](https://github.com/umccr/cttso-ica-to-pieriandx) repo; and to work along with @alexiswl there; as with #285. Sorry about the changes; now that we have a bit better idea on how to map out the data flow. Please see related [Trello card ](https://trello.com/c/tP3lwWGb/1017-redcap-slurp-data-from-it-to-the-portal-using-api) for more details, if any.

Thanks mate!

**Comment by victorskl** [comment]
Efforts are redirected to the dedicated repo https://github.com/umccr/redcap-apis

Closing
