### ISSUE TITLE
Linking ICA workflow runs to GDS-paths by placing workflow run uuid in path id

### ISSUE THREAD

**Issue by alexiswl** [umccr/data-portal-apis#348]
Proposal:

Three column database with the following columns:

id is a unique column expectation is that the other two columns are also unique columns.  

Portal Run ID will be a folder containing the working components in `gds://production/temp/` and outputs of the workflow in `gds://production/analysis_data/`

| id | portal_run_id      | ica_workflow_run_id |
|----|--------------------|---------------------|
| 1  | 2021-11-01-x16892c | wfr.12345678910     |
| 2  | 2021-11-02-yzw3end | wfr.10987543321     |
| 3  | 2021-10-02-zxefs23 | wfr.10982236331     |

**Comment by reisingerf** [comment]
This could perhaps even go directly into the workflow table?

That way we don't need a separate table and it would automatically be available via the API, right?
