### ISSUE TITLE
Add support for processing the active metadata sheet only

### ISSUE THREAD

**Issue by victorskl** [umccr/data-portal-apis#382]
**Context:**

- At the mo, the default strategy to sync LabMetadata from upstream Google Sheet is to **truncate & reload the whole table**.
- Therefore, we will need to reprocess all sheets every time.

**Actions:**

- [ ] Investigate a solution that does not need to truncate those "frozen" sheets 2020/2021
- [ ] (but only) Truncate & reload the "active" metadata sheet 2022

**Comment by fabform** [comment]
Handy to [find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)

**Comment by victorskl** [comment]
Added `wontfix` label as current processing on all sheets still take < 360 seconds.

Furthermore, there seem to have situation meta modification go back & ford through different sheets at any point in time. e.g. Someone need updating cell value from 2019 sheet to make some correction; so that it will go along well with 2023 sheet, etc.

Truncate & reload all, it is..!
