### ISSUE TITLE
Upgrade to RDS Aurora Serverless v2

### ISSUE THREAD

**Issue by victorskl** [umccr/data-portal-apis#450]
**Context:**

RDS Aurora Serverless v2 is GA -- https://aws.amazon.com/about-aws/whats-new/2022/04/amazon-aurora-serverless-v2/

Highlights:

> [...] delivering up to 90% cost savings compared to provisioning for peak capacity
> [...] available for the MySQL 8.0- and PostgreSQL 13-compatible editions
> [...] Scaling can change capacity by as little as 0.5 ACUs

Ditto -- https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-v2.html

**Actions:**

- Upgrade it
- Revisit cold start issue from ground 0

**Comment by brainstorm** [comment]
Hm, bummer, it does not scale to 0, apparently: https://twitter.com/mikebroberts/status/1517508862760427520

**Comment by brainstorm** [comment]
Far fetched and outside our AWS org, but I bumped into this: https://neon.tech

**Comment by victorskl** [comment]
Oi! 🙀 Nice, definitely checking it out...
