### ISSUE TITLE
Filter WES launch on succeeded runs

### ISSUE THREAD

**Issue by victorskl** [umccr/data-portal-apis#484]
**Context:**

- The `wes_handler` is a generic Lambda, of which all workflow run through its "launch" method for kicking off a run.

https://github.com/umccr/data-portal-apis/blob/ae1d95467bd15ccd722a95e8bc030e317a97c8e4/data_processors/pipeline/lambdas/wes_handler.py#L26-L34

**Cross-Cutting Concern:**

- Such that, workflow database lookup aggregate by `wfl.<ID>` and its version on Succeeded runs; within this history run records from database -- if there exists workflow's input JSON diff comparison (or compare `md5sum(input_json)`) is identical to the one staging for run input; then do not launch it.
- Perhaps, instead, notify Slack for detecting previously succeeded run exists.

**Actions:**

- Investigate & Implement

**Comment by reisingerf** [comment]
The input json comparison might be complicated by the addition of the "meta data" tag, as that may be different even if all other data are the same. 
Still worth investigating though, also if there are other conditions we should/could take into account before auto-launching a workflow.

**Comment by victorskl** [comment]
Ah, Right. Implication with this meta object stamp -- https://github.com/umccr/data-portal-apis/issues/485

**Comment by victorskl** [comment]
As with ICA v1 WES is sunsetting, won't consider this anymore. Something we may revisit more in future OrcaBus front. Closing.
