### ISSUE TITLE
ctTSO NTC should be run through ctTSO500 pipeline

### ISSUE THREAD

**Issue by alexiswl** [umccr/data-portal-apis#561]

**Comment by alexiswl** [comment]
@victorskl wondering best way to tackle this.

From https://github.com/umccr/data-portal-apis/blob/dev/data_processors/pipeline/orchestration/dragen_tso_ctdna_step.py#L91-L97

The NTC have the phenotype 'negative', but `must_be_tumor` selects only phenotypes that are 'tumor'.  

How can we do 'must_be_tumor() | must_be_ntc()'?

**Comment by reisingerf** [comment]
I guess the simplest is to add a `must_be_tumor_or_ntc`? 
Otherwise we'd have to deal with the AND/OR combination logic of rules.

**Comment by alexiswl** [comment]
Makes sense, just hoping we don't end up with too many combinations here otherwise.
