### ISSUE TITLE
Feature: Implement subject endpoint to include ctTSOv2 analysis results from ICAv2 BYOB

### ISSUE THREAD

**Issue by raylrui** [umccr/data-portal-apis#684]
## Feature

Add TSO V2 filter in the ~~GDSFileManager~~ ICAv2 BYOB for analysis results

## To Do
- [x] tsov2 metadata in the db
~~- [ ] the path format of tsov2 in the GDSFileManager~~

**Comment by victorskl** [comment]
This is on me. Please kindly wait. 

I will need to think a bit on how best to tackle showing results (key files of interest) from the new pipeline run in another system (ICAv2). This is not straight forward.

**Comment by raylrui** [comment]
sure, will update it when it is ready.

**Comment by victorskl** [comment]
As [discussed over Slack](https://umccr.slack.com/archives/CP356DDCH/p1718581843775209), taking over for API impl.
